appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ce13CtASamw7IQW9Nd0r2PsegNqDg4NgzR4UdeWleNK1L/3cAQOUPGpfQ6oeMMGTE7IOg4oKNdhRW6r92nHQbpDxPQ97IttTtstZed20Ea4QQoHnZhANNL2W1pDYalTRMjPnHelVyrx79AP7h1+UbeW45+CDn3b/VZg5m2hLyZxZcO7neJ29wVGSph2UYiA4FSb0b7Asv18FMa6sabNhaTFNatir89rCWVEXnryVt+RYxvYAjGsGfOwyWpGatxNTl6vt5VdyclOqUm6oxFt6MS5R3k0oqGRMOYm+pFvcgurlhXJs9frbyie4ubFVXormNk9GudSpBP8NrAr3D5Muhfn/wRkpBabMu7X/cGpJ3UMdLY0Q5tZyJVWiIrUybMVKLoP6JCSSK9oq0ybmWX5yPxec4yTPqBiGsn42Ofb0vLbwjfO339NUo6ufvAWZT6zY39WCTMh5bystVU0GPaq4JMK1/Ws5ZiNzLrXCdI1OL+7A0haXWHhgGKk5fi0xrgzoeYZIj66mcXM4n7GRdyOy94NLa3rf2Bttr/A38bq8Y1Kh7shyZIMMC4e9Y50GYVoxWfbCFvRIp9Hta56cbLPSzl8wZN54l4pZZ700Fmz9JuOHniIbN/9YfCJ1YlEc0TaijWo8/dgYZor/AzWrTnLGF4y2eT/s0NHhym+yzGHpwnI=}
provider:
  win: azure
bot:
  automerge: true
