travis:
  secure:
    BINSTAR_TOKEN: GLASmNKps3Yaih3ha6RV2F36V20nlzqQ+q/5P/z6uL6rji88LURyF8H+m1rNdwpbD2i1BYKOyb74rnhWpTlMEGtKNj8s3NE9zo6AEtHwQ30nXN4FiRMsLeuAQ2gfDdgIjl/Ipo9b1NRA+tECHZm+/TnBHkZR6NsIOY+rp3ts0pQzK6N2uKx3d+x/XH24EpsB4wts4BMf1Ttqez6PQsanxMEudfWNA4tJEHPDUS+imB/a/wr9KtvQi/IvRnS8/tX1v+Xk8pZWM365xcIRPg2qhrwE03bOBYtLMaZSuu84LPuaq+xRZUIgvTp7xI2ZnaRiaez+phVAEYueElNwlSu4pM3NCjPCiTTN88PQATGMky+rKi2UMZxybPvqgn8rmazF+SYBw3t5eo559tHm4WtOfHxWqF+v+xFvDkBo43rvUa+Y8EITTWqXf8Tja2Ag2XeqKlg1X7C+UZo7f38U8FGIvjLNtv45RMv1WFlWcyXIfoMHKxNmRxgsSOEghptJES/Ny1cDimViEibgUr/mqKAfNJ7zE1EEuRrJ7lJtj2UllygEDMiV9FbiCARwgmAOoe/zHd/thnUQDwY0vQuM+vqtfhY6hfaeBfpbw88XwgyLppV5MvGb2GDLs5GghEH47x83q/wqrx/O9TNgUl0r0l/aaraqIILz+VMVDRjYHXbFaKM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
